version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/terry-test

hooks:
  BeforeInstall:
    - location: ./scripts/initialize.sh
  AfterInstall:
    - location: ./scripts/buildImage.sh
      runas: root
  ApplicationStart:
    - location: ./scripts/start.sh
