version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/terry-stage # 배포될 위치
    overwrite: yes

permissions:
  - object: /home/ec2-user/terry-stage
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: ./deploy/deploy-stage.sh
      timeout: 300
      runas: root
#      runas: ec2-user
